// Copyright (c) 2019 Matias Furszyfer
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zerocoinj_JniBridge */

#ifndef _Included_com_zerocoinj_JniBridge
#define _Included_com_zerocoinj_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zerocoinj_JniBridge
 * Method:    compute1024seed
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zerocoinj_JniBridge_compute1024seed
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_zerocoinj_JniBridge
 * Method:    computeVSeedAndVExpanded
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zerocoinj_JniBridge_computeVSeedAndVExpanded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
